### ISSUE TITLE
Installer closes while installing OpenTabletDriver

### ISSUE THREAD

**Issue by heyimalex26** [OpenTabletDriver/OpenTabletDriver.Installer#36] opened 2021-03-26 06:47 UTC
During installation, the green bar reaches 100% but instead of finishing, the window just closes with no indication that the driver is installed.

**Comment by InfinityGhost** [comment] 2021-03-27 04:34
Hard crashing, good fun.

Try to reproduce this, then in event viewer you should be able to find a .NET Runtime Error in the applications section if you filter for it.

On a side note, this is to be deprecated in v0.6, since it will manage its own updating.

**Comment by heyimalex26** [comment] 2021-04-02 22:38
Huh. Tried it again after a couple of days and it worked. I tried everything I could but after restarting my PC and closing all background tasks it still failed to work. I eventually got restricted from downloading so I waited a few days, then tried again and it worked. Don't know what exactly went wrong, but I can't replicate it anymore.

**Comment by heyimalex26** [comment] 2021-04-02 22:56
Found the runtime error
The first error says this:

Application: OpenTabletDriver.Installer.exe
CoreCLR Version: 4.700.20.36602
.NET Core Version: 3.1.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException: Operation did not complete successfully because the file contains a virus or potentially unwanted software. : 'C:\Users\heyimalex26\AppData\Local\Temp\febc5745-a08d-4b12-ab80-8528d4d8e3fb.zip'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwriteFiles)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName)
   at InstallerLib.Installer.Install()
   at OpenTabletDriver.Installer.MainForm.Install(Boolean isUpdate)
   at OpenTabletDriver.Installer.MainForm.<.ctor>b__0_3(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Eto.Wpf.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Form mainForm)
   at OpenTabletDriver.Installer.Wpf.MainClass.Main(String[] args)


The second one says this:

Faulting application name: OpenTabletDriver.Installer.exe, version: 0.4.1.0, time stamp: 0x5f1757ad
Faulting module name: KERNELBASE.dll, version: 10.0.19041.804, time stamp: 0x0e9c5eae
Exception code: 0xe0434352
Fault offset: 0x000000000002d759
Faulting process ID: 0x13540
Faulting application start time: 0x01d7220afb0095d6
Faulting application path: C:\Users\heyimalex26\Downloads\OpenTabletDriver.Installer.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: ec6d60f1-7135-469c-b5bc-63be45fc1678
Faulting package full name:

**Comment by InfinityGhost** [comment] 2021-04-06 03:34
Has since been resolved with the false positive reports.

**Closed by InfinityGhost** 2021-04-06 03:34 UTC
Labels: bug
